[project]
name = "recipes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "taskipy>=1.14.1",
]
[tool.taskipy.tasks]
test = "python3 -m http.server 8072"